[package]
name = "ppl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.1"
rug = "1.18.0"
ast_derive = { path = "src/syntax/ast_derive" }
runtime = { path = "src/ir/runtime" }
miette = { version = "5.5.0", features = ["fancy"] }
thiserror = "1.0.37"
derive_more = "0.99.17"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0"] }
