[package]
name = "ppl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"
rug = "1.18.0"
ast_derive = { path = "src/ast_derive" }
miette = { version = "5.5.0", features = ["fancy"] }
thiserror = "1.0.37"
derive_more = "0.99.17"
runtime = { path = "src/runtime" }
enum_dispatch = "0.3.11"
clap = { version = "4.1.6", features = ["derive"] }
inkwell = { version = "0.2.0", features = ["llvm16-0"] }
pretty_env_logger = "0.5.0"
log = "0.4.20"
