[package]
name = "syntax"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
nom = "7.1.3"
once_cell = "1.17.1"
regex = "1.7.1"
thiserror = "1.0.40"
